### ISSUE TITLE
视频播放问题

### ISSUE THREAD

**Issue by Corezcy** [wansho/yunxuetang-script#1]
在视频菜单页界面，自动跳到菜单内最后一个视频播放，且最后一个视频播放完成后再次播放最后一个视频
无限套娃。
请教怎么解决啊？

**Comment by wansho** [comment]
脚本是写出来自用的，功能不完善，而且是现学的 JavaScript 语言，所以目前只能实现成这样了

**Comment by Corezcy** [comment]
> 脚本是写出来自用的，功能不完善，而且是现学的 JavaScript 语言，所以目前只能实现成这样了

准备现学改改看了，加油
